### ISSUE TITLE
what is version of tensorflow and  tensorlayer ？ thanks

### ISSUE THREAD

**Issue by hiredd** [alex04072000/SingleHDR#1]
good job ， could you please provide the version of the python packet ？

**Comment by alex04072000** [comment]
Hi @hiredd ,
Sorry, I forgot to mention that all the codes are tested using TensorFlow 1.10.0.
I will also add this to the readme.
Thank you!

**Comment by hiredd** [comment]
and what is the version of tensorlayer ？ thanks

**Comment by alex04072000** [comment]
Oops, forgot to mention.
It is 1.10.1 for tensorlayer.
