### ISSUE TITLE
Which tone mapping algorithm did you use?

### ISSUE THREAD

**Issue by UdonDa** [alex04072000/SingleHDR#27]
Hi, @alex04072000 

I try to reproduce to visualize HDR images with the HDR-Eye dataset.
However, I can not get the same results...

Please tell me which tone mapping algorithm you did?

Examples.
Use mu_law (below codes)
![ours](https://user-images.githubusercontent.com/25411643/131550864-76dfa6e8-7845-4781-995c-7220f7ef87f9.jpg)

Use Photomatix
![スクリーンショット 2021-09-01 2 45 00](https://user-images.githubusercontent.com/25411643/131550930-421198c9-9452-4656-8808-4733e3affe12.png)

Your result
![ours](https://user-images.githubusercontent.com/25411643/131551084-3021b24b-522d-4942-9836-27c52492e279.png)

Codes.
```
import numpy as np
import cv2

def mu_law(x, mu=10.):
    return np.log(1.0 + mu * x) / np.log(1.0 + mu)

def log(x):
    return np.log(x)

def main():

    FILENAME = 'gt'
    
    HDR_PATH  = f'/src/00004/{FILENAME}.hdr'

    img = cv2.imread(HDR_PATH) / 255.

    img = mu_law(img)
    # img = log(img)

    print(img.shape, img.max(), img.min())
    cv2.imwrite(f'./{FILENAME}.jpg', img * 255.)


if __name__ == '__main__':
    main()
```

**Comment by alex04072000** [comment]
Hi @UdonDa ,
We use the 'Vibrant' tone-mapping preset in Photomatix 6.0.
You can find the tone-mapping setting file in [path_of_photomatix]/BuiltinPresets/Vibrant.xmp.
Thank you!

**Comment by UdonDa** [comment]
Hi, @alex04072000 
Thanks!
I can reproduce the result!
Thank you!!
