### ISSUE TITLE
TypeError: __int__ returned non-int (type NoneType)

### ISSUE THREAD

**Issue by Hans1984** [alex04072000/SingleHDR#30]
Hi, 
Thanks for your excellent work, however, there are some problems when I try to run the test code. 
It appear **_'TypeError: __int__ returned non-int (type NoneType)'_**, seems some problem in the Upsample layer in deconcv-layer from hal-net.
I use tensorflow 1.10.
Could you give me some advice on it?

Thanks!

**Comment by Hans1984** [comment]
Solved.

**Comment by Conor-Kerrigan-Focal** [comment]
Same issue here, how did you fix it? @Hans1984

**Comment by Conor-Kerrigan-Focal** [comment]
Just fixed it be downgrading tensorflow to version 1.10.0
