### ISSUE TITLE
Release train code to update to Tensorflow 2.0

### ISSUE THREAD

**Issue by QLaHPD** [alex04072000/SingleHDR#7]
I'm having trouble running the script, I think it's being caused by incompatibilities between the versions of packages installed by pip and those installed by anaconda. 

Could you provide the training code so I can update to Tensorflow 2.0?

**Comment by szhang67** [comment]
I have the same issue here, when I try to run test_real_refinement.py. The tensorlayer requires tf version >= 2.0 while other imports like tensorflow.contrib, tensorflow.app require version < 2.0.

**Comment by weiwang90** [comment]
Hi, the tensorlayer version is also <2.0.  You can download with pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorlayer==1.X.X.

By the way, do you have the file ckpt.zip? 

> I have the same issue here, when I try to run test_real_refinement.py. The tensorlayer requires tf version >= 2.0 while other imports like tensorflow.contrib, tensorflow.app require version < 2.0.

**Comment by hongbojia** [comment]
Hi,there is a problem with the verson of tensorflow.The tensorflow.contrib coundn't run in the >=2.0 verson.But you want to use >=2.0 verson.It is is a contradiction.I don't know how can I use it.Thank you!!!
